// 00 · Inspect the file (read-only)
// Pages, collections, styles and the Inter / JetBrains Mono styles available.
// Generated by design/figma-scripts/build_scripts.py from design/tokens. Do not edit by hand.
// ---- shared prelude (identical in every step) ----
const hex = (h) => ({ r: parseInt(h.slice(1, 3), 16) / 255, g: parseInt(h.slice(3, 5), 16) / 255, b: parseInt(h.slice(5, 7), 16) / 255 });
const rgba = (h, a) => Object.assign(hex(h), { a: a === undefined ? 1 : a });
const collections = await figma.variables.getLocalVariableCollectionsAsync();
const allVars = await figma.variables.getLocalVariablesAsync();
const report = { created: [], updated: [], warnings: [] };
function ensureCollection(name, modeNames) {
  let c = collections.find((x) => x.name === name);
  if (!c) { c = figma.variables.createVariableCollection(name); collections.push(c); report.created.push(c.id); }
  modeNames.forEach((m, i) => {
    if (i < c.modes.length) { if (c.modes[i].name !== m) c.renameMode(c.modes[i].modeId, m); }
    else { try { c.addMode(m); } catch (e) { report.warnings.push(`addMode ${name}/${m}: ${e.message} (plan without modes?)`); } }
  });
  return c;
}
const modeId = (c, name) => (c.modes.find((m) => m.name === name) || c.modes[0]).modeId;
function ensureVar(c, name, type) {
  let v = allVars.find((x) => x.variableCollectionId === c.id && x.name === name);
  if (v && v.resolvedType !== type) throw new Error(`type clash on ${name}: ${v.resolvedType} vs ${type}`);
  if (!v) { v = figma.variables.createVariable(name, c, type); allVars.push(v); report.created.push(v.id); }
  else report.updated.push(v.id);
  return v;
}
function findVar(collectionName, name) {
  const c = collections.find((x) => x.name === collectionName);
  const v = c && allVars.find((x) => x.variableCollectionId === c.id && x.name === name);
  if (!v) throw new Error(`missing variable ${collectionName} / ${name}: run the earlier step first`);
  return v;
}
const alias = (v) => ({ type: 'VARIABLE_ALIAS', id: v.id });
const camel = (parts) => parts.map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('');
function codeSyntax(v) {
  const parts = v.name.split('/');
  const ns = 'DS' + parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
  v.setVariableCodeSyntax('WEB', `var(--${parts.join('-')})`);
  v.setVariableCodeSyntax('ANDROID', `${ns}.${camel(parts.slice(1))}`);
  v.setVariableCodeSyntax('iOS', `${ns}.${camel(parts.slice(1))}`);
}
// ---- end prelude ----
// Read-only. Run first; it changes nothing.
const pages = figma.root.children.map((p) => ({ id: p.id, name: p.name }));
const textStyles = (await figma.getLocalTextStylesAsync()).map((s) => s.name);
const effectStyles = (await figma.getLocalEffectStylesAsync()).map((s) => s.name);
const cols = collections.map((c) => ({ id: c.id, name: c.name, modes: c.modes.map((m) => m.name),
  variables: allVars.filter((v) => v.variableCollectionId === c.id).length }));
const fonts = (await figma.listAvailableFontsAsync()).filter((f) => ['Inter', 'JetBrains Mono'].includes(f.fontName.family)).map((f) => `${f.fontName.family} ${f.fontName.style}`);
return { fileName: figma.root.name, pages, collections: cols, textStyles, effectStyles, fonts };
