// 06 · Motion collection (Standard, Reduced)
// Durations, easings and transitions.
// Generated by design/figma-scripts/build_scripts.py from design/tokens. Do not edit by hand.
// ---- shared prelude (identical in every step) ----
const hex = (h) => ({ r: parseInt(h.slice(1, 3), 16) / 255, g: parseInt(h.slice(3, 5), 16) / 255, b: parseInt(h.slice(5, 7), 16) / 255 });
const rgba = (h, a) => Object.assign(hex(h), { a: a === undefined ? 1 : a });
const collections = await figma.variables.getLocalVariableCollectionsAsync();
const allVars = await figma.variables.getLocalVariablesAsync();
const report = { created: [], updated: [], warnings: [] };
function ensureCollection(name, modeNames) {
  let c = collections.find((x) => x.name === name);
  if (!c) { c = figma.variables.createVariableCollection(name); collections.push(c); report.created.push(c.id); }
  modeNames.forEach((m, i) => {
    if (i < c.modes.length) { if (c.modes[i].name !== m) c.renameMode(c.modes[i].modeId, m); }
    else { try { c.addMode(m); } catch (e) { report.warnings.push(`addMode ${name}/${m}: ${e.message} (plan without modes?)`); } }
  });
  return c;
}
const modeId = (c, name) => (c.modes.find((m) => m.name === name) || c.modes[0]).modeId;
function ensureVar(c, name, type) {
  let v = allVars.find((x) => x.variableCollectionId === c.id && x.name === name);
  if (v && v.resolvedType !== type) throw new Error(`type clash on ${name}: ${v.resolvedType} vs ${type}`);
  if (!v) { v = figma.variables.createVariable(name, c, type); allVars.push(v); report.created.push(v.id); }
  else report.updated.push(v.id);
  return v;
}
function findVar(collectionName, name) {
  const c = collections.find((x) => x.name === collectionName);
  const v = c && allVars.find((x) => x.variableCollectionId === c.id && x.name === name);
  if (!v) throw new Error(`missing variable ${collectionName} / ${name}: run the earlier step first`);
  return v;
}
const alias = (v) => ({ type: 'VARIABLE_ALIAS', id: v.id });
const camel = (parts) => parts.map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('');
function codeSyntax(v) {
  const parts = v.name.split('/');
  const ns = 'DS' + parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
  v.setVariableCodeSyntax('WEB', `var(--${parts.join('-')})`);
  v.setVariableCodeSyntax('ANDROID', `${ns}.${camel(parts.slice(1))}`);
  v.setVariableCodeSyntax('iOS', `${ns}.${camel(parts.slice(1))}`);
}
// ---- end prelude ----
const DATA = {"durations":[["motion/duration/instant","motion/duration/0"],["motion/duration/micro","motion/duration/100"],["motion/duration/short","motion/duration/150"],["motion/duration/medium","motion/duration/200"],["motion/duration/long","motion/duration/300"],["motion/duration/xlong","motion/duration/400"]],"easings":{"motion/easing/standard":"cubic-bezier(0.2, 0, 0, 1)","motion/easing/enter":"cubic-bezier(0, 0, 0, 1)","motion/easing/exit":"cubic-bezier(0.3, 0, 1, 1)","motion/easing/linear":"cubic-bezier(0, 0, 1, 1)"},"easingRows":[["motion/easing/standard","cubic-bezier(0.2, 0, 0, 1)","Moving and morphing on screen."],["motion/easing/enter","cubic-bezier(0, 0, 0, 1)","Entering: strong decelerate."],["motion/easing/exit","cubic-bezier(0.3, 0, 1, 1)","Leaving: accelerate out of the way."],["motion/easing/linear","cubic-bezier(0, 0, 1, 1)","Spinners and progress only."]],"transitions":[["motion/transition/feedback","motion/duration/micro","motion/duration/micro","motion/easing/standard","motion/easing/standard"],["motion/transition/enter","motion/duration/medium","motion/duration/micro","motion/easing/enter","motion/easing/standard"],["motion/transition/exit","motion/duration/short","motion/duration/micro","motion/easing/exit","motion/easing/standard"]]};
// Motion: Standard and Reduced modes (reduced motion as a token mode, DC-L04-25). Easing is stored as a CSS
// cubic-bezier STRING; Figma's EASING type exists but its value shape was not verified (see figma-plan.md).
const c = ensureCollection('Motion', ['Standard', 'Reduced']);
const S = modeId(c, 'Standard'), R = modeId(c, 'Reduced');
const prim = (n) => findVar('Primitives', n);
const durType = prim(DATA.durations[0][1]).resolvedType;
for (const [name, target] of DATA.durations) {
  const v = ensureVar(c, name, durType); v.setValueForMode(S, alias(prim(target))); v.setValueForMode(R, alias(prim(target))); v.scopes = []; codeSyntax(v);
}
for (const [name, css, description] of DATA.easingRows) {
  const v = ensureVar(c, name, 'STRING'); v.setValueForMode(S, css); v.setValueForMode(R, css); v.scopes = []; v.description = description; codeSyntax(v);
}
for (const [name, dStd, dRed, eStd, eRed] of DATA.transitions) {
  const d = ensureVar(c, name + '/duration', durType);
  d.setValueForMode(S, alias(findVar('Motion', dStd))); d.setValueForMode(R, alias(findVar('Motion', dRed))); d.scopes = []; codeSyntax(d);
  const e = ensureVar(c, name + '/easing', 'STRING');
  e.setValueForMode(S, alias(findVar('Motion', eStd))); e.setValueForMode(R, alias(findVar('Motion', eRed))); e.scopes = []; codeSyntax(e);
}
return { collection: c.id, durationType: durType, variables: allVars.filter((v) => v.variableCollectionId === c.id).length, warnings: report.warnings };
