// 07 · Effect styles
// elevation/raised, elevation/overlay, focus/ring with variable-bound colors.
// Generated by design/figma-scripts/build_scripts.py from design/tokens. Do not edit by hand.
// ---- shared prelude (identical in every step) ----
const hex = (h) => ({ r: parseInt(h.slice(1, 3), 16) / 255, g: parseInt(h.slice(3, 5), 16) / 255, b: parseInt(h.slice(5, 7), 16) / 255 });
const rgba = (h, a) => Object.assign(hex(h), { a: a === undefined ? 1 : a });
const collections = await figma.variables.getLocalVariableCollectionsAsync();
const allVars = await figma.variables.getLocalVariablesAsync();
const report = { created: [], updated: [], warnings: [] };
function ensureCollection(name, modeNames) {
  let c = collections.find((x) => x.name === name);
  if (!c) { c = figma.variables.createVariableCollection(name); collections.push(c); report.created.push(c.id); }
  modeNames.forEach((m, i) => {
    if (i < c.modes.length) { if (c.modes[i].name !== m) c.renameMode(c.modes[i].modeId, m); }
    else { try { c.addMode(m); } catch (e) { report.warnings.push(`addMode ${name}/${m}: ${e.message} (plan without modes?)`); } }
  });
  return c;
}
const modeId = (c, name) => (c.modes.find((m) => m.name === name) || c.modes[0]).modeId;
function ensureVar(c, name, type) {
  let v = allVars.find((x) => x.variableCollectionId === c.id && x.name === name);
  if (v && v.resolvedType !== type) throw new Error(`type clash on ${name}: ${v.resolvedType} vs ${type}`);
  if (!v) { v = figma.variables.createVariable(name, c, type); allVars.push(v); report.created.push(v.id); }
  else report.updated.push(v.id);
  return v;
}
function findVar(collectionName, name) {
  const c = collections.find((x) => x.name === collectionName);
  const v = c && allVars.find((x) => x.variableCollectionId === c.id && x.name === name);
  if (!v) throw new Error(`missing variable ${collectionName} / ${name}: run the earlier step first`);
  return v;
}
const alias = (v) => ({ type: 'VARIABLE_ALIAS', id: v.id });
const camel = (parts) => parts.map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('');
function codeSyntax(v) {
  const parts = v.name.split('/');
  const ns = 'DS' + parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
  v.setVariableCodeSyntax('WEB', `var(--${parts.join('-')})`);
  v.setVariableCodeSyntax('ANDROID', `${ns}.${camel(parts.slice(1))}`);
  v.setVariableCodeSyntax('iOS', `${ns}.${camel(parts.slice(1))}`);
}
// ---- end prelude ----
const DATA = [{"name":"elevation/shadow/raised","layers":[{"color":"color/shadow/soft","x":0,"y":1,"blur":2,"spread":0},{"color":"color/shadow/soft","x":0,"y":2,"blur":8,"spread":0}],"description":"Cards, sticky headers, dragged rows. 1px contact + soft blur."},{"name":"elevation/shadow/overlay","layers":[{"color":"color/shadow/soft","x":0,"y":1,"blur":2,"spread":0},{"color":"color/shadow/strong","x":0,"y":8,"blur":24,"spread":-4},{"color":"color/shadow/ring","x":0,"y":0,"blur":0,"spread":1}],"description":"Menus, popovers, dialogs. Negative spread tucks the ambient layer; the ring shows only in dark."},{"name":"focus/ring","description":"Focus-visible ring: 2px gap in the surface color, then a 2px border.focus ring (DC-L04-09).","layers":[{"color":"color/surface/raised","x":0,"y":0,"blur":0,"spread":2},{"color":"color/border/focus","x":0,"y":0,"blur":0,"spread":4}]}];
// Effect styles whose shadow colors are bound to Color variables, so Light/Dark switches the shadow (DC-L04-12).
const existing = await figma.getLocalEffectStylesAsync();
const ids = [];
for (const st of DATA) {
  let es = existing.find((x) => x.name === st.name);
  if (!es) { es = figma.createEffectStyle(); es.name = st.name; report.created.push(es.id); }
  es.effects = st.layers.map((l) => figma.variables.setBoundVariableForEffect(
    { type: 'DROP_SHADOW', color: { r: 0, g: 0, b: 0, a: 0.1 }, offset: { x: l.x, y: l.y }, radius: l.blur, spread: l.spread,
      visible: true, blendMode: 'NORMAL', showShadowBehindNode: false }, 'color', findVar('Color', l.color)));
  es.description = st.description;
  ids.push(es.id);
}
return { effectStyles: ids, created: report.created.length };
