// 08 · Icon components
// icon/plus and icon/spinner on the Components page.
// Generated by design/figma-scripts/build_scripts.py from design/tokens. Do not edit by hand.
// ---- shared prelude (identical in every step) ----
const hex = (h) => ({ r: parseInt(h.slice(1, 3), 16) / 255, g: parseInt(h.slice(3, 5), 16) / 255, b: parseInt(h.slice(5, 7), 16) / 255 });
const rgba = (h, a) => Object.assign(hex(h), { a: a === undefined ? 1 : a });
const collections = await figma.variables.getLocalVariableCollectionsAsync();
const allVars = await figma.variables.getLocalVariablesAsync();
const report = { created: [], updated: [], warnings: [] };
function ensureCollection(name, modeNames) {
  let c = collections.find((x) => x.name === name);
  if (!c) { c = figma.variables.createVariableCollection(name); collections.push(c); report.created.push(c.id); }
  modeNames.forEach((m, i) => {
    if (i < c.modes.length) { if (c.modes[i].name !== m) c.renameMode(c.modes[i].modeId, m); }
    else { try { c.addMode(m); } catch (e) { report.warnings.push(`addMode ${name}/${m}: ${e.message} (plan without modes?)`); } }
  });
  return c;
}
const modeId = (c, name) => (c.modes.find((m) => m.name === name) || c.modes[0]).modeId;
function ensureVar(c, name, type) {
  let v = allVars.find((x) => x.variableCollectionId === c.id && x.name === name);
  if (v && v.resolvedType !== type) throw new Error(`type clash on ${name}: ${v.resolvedType} vs ${type}`);
  if (!v) { v = figma.variables.createVariable(name, c, type); allVars.push(v); report.created.push(v.id); }
  else report.updated.push(v.id);
  return v;
}
function findVar(collectionName, name) {
  const c = collections.find((x) => x.name === collectionName);
  const v = c && allVars.find((x) => x.variableCollectionId === c.id && x.name === name);
  if (!v) throw new Error(`missing variable ${collectionName} / ${name}: run the earlier step first`);
  return v;
}
const alias = (v) => ({ type: 'VARIABLE_ALIAS', id: v.id });
const camel = (parts) => parts.map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('');
function codeSyntax(v) {
  const parts = v.name.split('/');
  const ns = 'DS' + parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
  v.setVariableCodeSyntax('WEB', `var(--${parts.join('-')})`);
  v.setVariableCodeSyntax('ANDROID', `${ns}.${camel(parts.slice(1))}`);
  v.setVariableCodeSyntax('iOS', `${ns}.${camel(parts.slice(1))}`);
}
// ---- end prelude ----
// Icon components used by Button (instance swap needs a real component). Strokes bound to color/icon/default.
const page = figma.root.children.find((p) => p.name === 'Components');
if (!page) throw new Error('run 01-pages first');
await figma.setCurrentPageAsync(page);
const ICONS = {
  'icon/plus': '<svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 3.5v9M3.5 8h9" stroke="#000" stroke-width="1.5" stroke-linecap="round"/></svg>',
  'icon/spinner': '<svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 2.5a5.5 5.5 0 0 1 5.5 5.5" stroke="#000" stroke-width="2" stroke-linecap="round"/></svg>',
};
const iconColor = findVar('Color', 'color/icon/default');
const ids = {};
let x = 0;
for (const [name, svg] of Object.entries(ICONS)) {
  let comp = page.findOne((n) => n.type === 'COMPONENT' && n.name === name);
  if (!comp) {
    const node = figma.createNodeFromSvg(svg);
    comp = figma.createComponent(); comp.name = name; comp.resize(16, 16); comp.clipsContent = true;
    for (const child of [...node.children]) comp.appendChild(child);
    node.remove();
    comp.x = x; comp.y = -120; x += 40;
    report.created.push(comp.id);
  }
  comp.findAllWithCriteria({ types: ['VECTOR'] }).forEach((v) => {
    v.strokes = [figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: { r: 0, g: 0, b: 0 } }, 'color', iconColor)];
  });
  comp.description = name === 'icon/plus' ? 'Default leading icon for Button.' : 'Loading spinner for Button (replaces the icon).';
  ids[name] = comp.id;
}
return { icons: ids, created: report.created };
