#!/usr/bin/env python3
"""Generate the ordered use_figma scripts (and Paper token list) from design/tokens (stdlib only).

    python3 design/figma-scripts/build_scripts.py

Each NN-*.js file is the `code` argument for one `use_figma` call. Scripts follow Figma's figma-use
rules (fetched 2026-09-23): plain JS, top-level await, `return` for output, no IIFE, explicit scopes,
one page switch per call, and every created/mutated id returned. Every script is idempotent: it finds
collections, variables, styles and components by name and updates them instead of duplicating.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOK = os.path.join(HERE, "..", "tokens")
sys.path.insert(0, TOK)
from check_contrast import _flatten, _load, resolve  # noqa: E402

NS = "dev.dsbuilder"


def flat(name):
    out = {}
    _flatten(_load(name), "", None, out)
    return out


def fig(path):
    return path.replace(".", "/")


def alias_target(v):
    return fig(v[1:-1]) if isinstance(v, str) and v.startswith("{") else None


PRELUDE = r"""// ---- shared prelude (identical in every step) ----
const hex = (h) => ({ r: parseInt(h.slice(1, 3), 16) / 255, g: parseInt(h.slice(3, 5), 16) / 255, b: parseInt(h.slice(5, 7), 16) / 255 });
const rgba = (h, a) => Object.assign(hex(h), { a: a === undefined ? 1 : a });
const collections = await figma.variables.getLocalVariableCollectionsAsync();
const allVars = await figma.variables.getLocalVariablesAsync();
const report = { created: [], updated: [], warnings: [] };
function ensureCollection(name, modeNames) {
  let c = collections.find((x) => x.name === name);
  if (!c) { c = figma.variables.createVariableCollection(name); collections.push(c); report.created.push(c.id); }
  modeNames.forEach((m, i) => {
    if (i < c.modes.length) { if (c.modes[i].name !== m) c.renameMode(c.modes[i].modeId, m); }
    else { try { c.addMode(m); } catch (e) { report.warnings.push(`addMode ${name}/${m}: ${e.message} (plan without modes?)`); } }
  });
  return c;
}
const modeId = (c, name) => (c.modes.find((m) => m.name === name) || c.modes[0]).modeId;
function ensureVar(c, name, type) {
  let v = allVars.find((x) => x.variableCollectionId === c.id && x.name === name);
  if (v && v.resolvedType !== type) throw new Error(`type clash on ${name}: ${v.resolvedType} vs ${type}`);
  if (!v) { v = figma.variables.createVariable(name, c, type); allVars.push(v); report.created.push(v.id); }
  else report.updated.push(v.id);
  return v;
}
function findVar(collectionName, name) {
  const c = collections.find((x) => x.name === collectionName);
  const v = c && allVars.find((x) => x.variableCollectionId === c.id && x.name === name);
  if (!v) throw new Error(`missing variable ${collectionName} / ${name}: run the earlier step first`);
  return v;
}
const alias = (v) => ({ type: 'VARIABLE_ALIAS', id: v.id });
const camel = (parts) => parts.map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('');
function codeSyntax(v) {
  const parts = v.name.split('/');
  const ns = 'DS' + parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
  v.setVariableCodeSyntax('WEB', `var(--${parts.join('-')})`);
  v.setVariableCodeSyntax('ANDROID', `${ns}.${camel(parts.slice(1))}`);
  v.setVariableCodeSyntax('iOS', `${ns}.${camel(parts.slice(1))}`);
}
// ---- end prelude ----
"""


def script(num, title, doc, data, body):
    head = f"// {num} · {title}\n// {doc}\n// Generated by design/figma-scripts/build_scripts.py from design/tokens. Do not edit by hand.\n"
    data_js = "" if data is None else f"const DATA = {json.dumps(data, separators=(',', ':'))};\n"
    return head + PRELUDE + data_js + body.strip() + "\n"


# ------------------------------------------------------------------ data

def primitives_data():
    cp = flat("color.primitives.tokens.json")
    colors = [[fig(p), t["$value"]["hex"]] for p, t in cp.items()]
    sp = flat("spacing.tokens.json")
    space = [[fig(p), t["$value"]["value"]] for p, t in sp.items()
             if p.startswith("space.") and isinstance(t["$value"], dict) and p.count(".") == 1]
    rd = flat("radius.tokens.json")
    radius = [[fig(p), t["$value"]["value"]] for p, t in rd.items() if p.startswith("radius.") and isinstance(t["$value"], dict)]
    bw = [[fig(p), t["$value"]["value"]] for p, t in rd.items() if p.startswith("border.width.") and isinstance(t["$value"], dict)]
    mo = flat("motion.tokens.json")
    dur = [[fig(p), t["$value"]["value"] / 1000] for p, t in mo.items()
           if p.startswith("motion.duration.") and isinstance(t["$value"], dict)]
    return {"colors": colors, "floats": space + radius + bw, "durations": dur}


SCOPES = [
    ("color/surface/", ["FRAME_FILL", "SHAPE_FILL"]), ("color/bg/", ["FRAME_FILL", "SHAPE_FILL"]),
    ("color/text/", ["TEXT_FILL"]), ("color/icon/", ["SHAPE_FILL", "STROKE_COLOR"]),
    ("color/border/", ["STROKE_COLOR"]), ("color/overlay/", ["FRAME_FILL"]), ("color/shadow/", ["EFFECT_COLOR"]),
]


def scopes_for(name):
    for prefix, sc in SCOPES:
        if name.startswith(prefix):
            return sc
    raise KeyError(name)


def color_data():
    light, dark = flat("color.light.tokens.json"), flat("color.dark.tokens.json")
    rows = []
    for p, t in light.items():
        lv, dv = t["$value"], dark[p]["$value"]
        enc = lambda v: {"alias": alias_target(v)} if alias_target(v) else {"hex": v["hex"], "a": v.get("alpha", 1)}
        rows.append([fig(p), enc(lv), enc(dv), scopes_for(fig(p)), t["$description"]])
    return rows


def spacing_radius_data():
    comfy, compact = flat("spacing.comfortable.tokens.json"), flat("spacing.compact.tokens.json")
    sp, rd = flat("spacing.tokens.json"), flat("radius.tokens.json")
    spacing = [[fig(p), alias_target(t["$value"]), alias_target(compact[p]["$value"]), ["GAP"], t.get("$description", "")] for p, t in comfy.items()]
    for p, t in sp.items():
        if p.startswith("space.layout."):
            spacing.append([fig(p), alias_target(t["$value"]), alias_target(t["$value"]), ["GAP"], t["$description"]])
        elif p.startswith("size."):
            spacing.append([fig(p), {"value": t["$value"]["value"]}, {"value": t["$value"]["value"]}, ["WIDTH_HEIGHT"], t.get("$description", "")])
    radius = []
    for p, t in rd.items():
        v = t["$value"]
        if p.startswith("radius.") and (alias_target(v) or p == "radius.full"):
            radius.append([fig(p), alias_target(v) or fig(p), ["CORNER_RADIUS"], t.get("$description", "")])
        elif p.startswith("border.width.") and alias_target(v):
            radius.append([fig(p), alias_target(v), ["STROKE_FLOAT"], t.get("$description", "")])
        elif p.startswith("focus.ring."):
            radius.append([fig(p), alias_target(v) if alias_target(v) else {"value": v["value"]}, ["STROKE_FLOAT", "EFFECT_FLOAT"], ""])
    return {"spacing": spacing, "radius": radius}


def typography_data():
    ty = flat("typography.tokens.json")
    fam = {"font/family/sans": "Inter", "font/family/mono": "JetBrains Mono"}
    floats = [[fig(p), t["$value"] if isinstance(t["$value"], (int, float)) else t["$value"]["value"],
               {"weight": "FONT_WEIGHT", "size": "FONT_SIZE", "lineHeight": "LINE_HEIGHT"}[p.split(".")[1]]]
              for p, t in ty.items() if p.startswith("font.") and not p.startswith("font.family")]
    styles = []
    r = resolve()
    for p, t in ty.items():
        if not p.startswith("text."):
            continue
        ext = t["$extensions"][NS]
        v = r[p]["resolved"]
        styles.append({"name": fig(p), "family": "mono" if "JetBrains Mono" in v["fontFamily"] else "sans",
                       "weight": v["fontWeight"], "size": fig(ext["fontSizeRef"]), "line": fig(ext["lineHeightRef"]),
                       "tracking": v["letterSpacing"]["value"], "upper": ext.get("textTransform") == "uppercase",
                       "description": f"Use: {ext['use']} Avoid: {ext['avoid']}"})
    return {"families": [[k, v] for k, v in fam.items()], "floats": floats, "styles": styles}


def motion_data():
    mo, std, red = flat("motion.tokens.json"), flat("motion.standard.tokens.json"), flat("motion.reduced.tokens.json")
    durations = [[fig(p), alias_target(t["$value"])] for p, t in mo.items() if p.startswith("motion.duration.") and alias_target(t["$value"])]
    easings = [[fig(p), "cubic-bezier(" + ", ".join(f"{x:g}" for x in t["$value"]) + ")", t["$description"]]
               for p, t in mo.items() if p.startswith("motion.easing.")]
    transitions = []
    for p, t in std.items():
        s, rr = t["$value"], red[p]["$value"]
        transitions.append([fig(p), alias_target(s["duration"]), alias_target(rr["duration"]),
                            alias_target(s["timingFunction"]), alias_target(rr["timingFunction"])])
    return {"durations": durations, "easings": dict((e[0], e[1]) for e in easings), "easingRows": easings, "transitions": transitions}


def effects_data():
    el = flat("elevation.tokens.json")
    out = []
    for p, t in el.items():
        layers = [{"color": alias_target(l["color"]), "x": l["offsetX"]["value"], "y": l["offsetY"]["value"],
                   "blur": l["blur"]["value"], "spread": l["spread"]["value"]} for l in t["$value"]]
        out.append({"name": fig(p), "layers": layers, "description": t["$description"]})
    out.append({"name": "focus/ring", "description": "Focus-visible ring: 2px gap in the surface color, then a 2px border.focus ring (DC-L04-09).",
                "layers": [{"color": "color/surface/raised", "x": 0, "y": 0, "blur": 0, "spread": 2},
                           {"color": "color/border/focus", "x": 0, "y": 0, "blur": 0, "spread": 4}]})
    return out


BUTTON_VARIANTS = {
    "Primary": {"rest": "color/bg/accent/bold", "hover": "color/bg/accent/boldHover", "pressed": "color/bg/accent/boldPressed",
                "label": "color/text/onAccent", "border": None, "disabledFill": "color/bg/disabled"},
    "Secondary": {"rest": "color/bg/neutral/subtle", "hover": "color/bg/neutral/subtleHover", "pressed": "color/bg/neutral/subtlePressed",
                  "label": "color/text/primary", "border": None, "disabledFill": "color/bg/disabled"},
    "Outline": {"rest": None, "hover": "color/bg/neutral/subtle", "pressed": "color/bg/neutral/subtlePressed",
                "label": "color/text/primary", "border": "color/border/default", "disabledFill": None},
    "Ghost": {"rest": None, "hover": "color/bg/neutral/subtle", "pressed": "color/bg/neutral/subtlePressed",
              "label": "color/text/primary", "border": None, "disabledFill": None},
    "Danger": {"rest": "color/bg/danger/bold", "hover": "color/bg/danger/boldHover", "pressed": "color/bg/danger/boldPressed",
               "label": "color/text/onDanger", "border": None, "disabledFill": "color/bg/disabled"},
}
BUTTON_LABELS = {"Primary": "Save changes", "Secondary": "Preview", "Outline": "Export", "Ghost": "Cancel", "Danger": "Delete file"}


# ------------------------------------------------------------------ bodies

INSPECT = r"""
// Read-only. Run first; it changes nothing.
const pages = figma.root.children.map((p) => ({ id: p.id, name: p.name }));
const textStyles = (await figma.getLocalTextStylesAsync()).map((s) => s.name);
const effectStyles = (await figma.getLocalEffectStylesAsync()).map((s) => s.name);
const cols = collections.map((c) => ({ id: c.id, name: c.name, modes: c.modes.map((m) => m.name),
  variables: allVars.filter((v) => v.variableCollectionId === c.id).length }));
const fonts = (await figma.listAvailableFontsAsync()).filter((f) => ['Inter', 'JetBrains Mono'].includes(f.fontName.family)).map((f) => `${f.fontName.family} ${f.fontName.style}`);
return { fileName: figma.root.name, pages, collections: cols, textStyles, effectStyles, fonts };
"""

PAGES = r"""
const WANT = ['Cover', 'Foundations', 'Components', 'Atlas · Building blocks', 'Atlas · Builder concept'];
const out = [];
for (const name of WANT) {
  let p = figma.root.children.find((x) => x.name === name);
  if (!p) { p = figma.createPage(); p.name = name; report.created.push(p.id); }
  out.push({ name, id: p.id });
}
return { pages: out, ...report };
"""

PRIMITIVES = r"""
// Primitives: one mode, hidden from publishing, no scopes (pickers never show them) (DC-L07-18, DC-L07-19).
const c = ensureCollection('Primitives', ['Value']);
c.hiddenFromPublishing = true;
const m = modeId(c, 'Value');
for (const [name, h] of DATA.colors) { const v = ensureVar(c, name, 'COLOR'); v.setValueForMode(m, rgba(h)); v.scopes = []; v.hiddenFromPublishing = true; codeSyntax(v); }
for (const [name, px] of DATA.floats) { const v = ensureVar(c, name, 'FLOAT'); v.setValueForMode(m, px); v.scopes = []; v.hiddenFromPublishing = true; codeSyntax(v); }
// Durations: TIMING variables take seconds (Figma Motion). Fall back to FLOAT milliseconds if TIMING is unavailable.
let timingType = 'TIMING';
for (const [name, sec] of DATA.durations) {
  let v;
  try { v = ensureVar(c, name, timingType); v.setValueForMode(m, timingType === 'TIMING' ? sec : sec * 1000); }
  catch (e) { if (timingType === 'TIMING') { timingType = 'FLOAT'; report.warnings.push('TIMING unavailable, durations stored as FLOAT ms: ' + e.message); v = ensureVar(c, name, 'FLOAT'); v.setValueForMode(m, sec * 1000); } else throw e; }
  v.scopes = []; v.hiddenFromPublishing = true; codeSyntax(v);
}
return { collection: c.id, variables: allVars.filter((v) => v.variableCollectionId === c.id).length, timingType,
  created: report.created.length, updated: report.updated.length, warnings: report.warnings };
"""

COLOR = r"""
// Semantic color: Light and Dark modes, aliases into Primitives, scoped by property (DC-L01-18, DC-L07-19, DC-L07-20).
const c = ensureCollection('Color', ['Light', 'Dark']);
const L = modeId(c, 'Light'), D = modeId(c, 'Dark');
const val = (x) => (x.alias ? alias(findVar('Primitives', x.alias)) : rgba(x.hex, x.a));
for (const [name, light, dark, scopes, description] of DATA) {
  const v = ensureVar(c, name, 'COLOR');
  v.setValueForMode(L, val(light)); v.setValueForMode(D, val(dark));
  v.scopes = scopes; v.description = description; codeSyntax(v);
}
return { collection: c.id, modes: c.modes.map((x) => x.name), variables: allVars.filter((v) => v.variableCollectionId === c.id).length,
  created: report.created.length, updated: report.updated.length, warnings: report.warnings };
"""

SPACING_RADIUS = r"""
// Spacing: Comfortable and Compact density modes (DC-L03-11). Radius: one mode. Sizes do not change with density.
const s = ensureCollection('Spacing', ['Comfortable', 'Compact']);
const SC = modeId(s, 'Comfortable'), SK = modeId(s, 'Compact');
const num = (x) => (typeof x === 'string' ? alias(findVar('Primitives', x)) : x.value);
for (const [name, comfy, compact, scopes, description] of DATA.spacing) {
  const v = ensureVar(s, name, 'FLOAT');
  v.setValueForMode(SC, num(comfy)); v.setValueForMode(SK, num(compact));
  v.scopes = scopes; v.description = description; codeSyntax(v);
}
const r = ensureCollection('Radius', ['Default']);
const R = modeId(r, 'Default');
for (const [name, target, scopes, description] of DATA.radius) {
  const v = ensureVar(r, name, 'FLOAT');
  v.setValueForMode(R, num(target)); v.scopes = scopes; v.description = description; codeSyntax(v);
}
return { spacing: s.id, radius: r.id, created: report.created.length, updated: report.updated.length, warnings: report.warnings };
"""

TYPOGRAPHY = r"""
// Typography variables plus 15 text styles bound to them ("variables for values, styles for bundles", DC-L07-21, DC-L02-28).
const c = ensureCollection('Typography', ['Default']);
const M = modeId(c, 'Default');
const available = await figma.listAvailableFontsAsync();
const styleFor = (family, weight) => {
  const want = { 400: ['Regular'], 500: ['Medium'], 600: ['Semi Bold', 'SemiBold'] }[weight];
  const f = available.find((x) => x.fontName.family === family && want.includes(x.fontName.style));
  return f ? f.fontName : null;
};
let mono = 'JetBrains Mono';
if (!styleFor(mono, 400)) { mono = 'Roboto Mono'; report.warnings.push('JetBrains Mono not available; using Roboto Mono'); }
const familyName = { sans: 'Inter', mono };
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
await figma.loadFontAsync({ family: mono, style: 'Regular' });
for (const [name, fam] of DATA.families) {
  const v = ensureVar(c, name, 'STRING'); v.setValueForMode(M, name.endsWith('mono') ? mono : fam); v.scopes = ['FONT_FAMILY']; codeSyntax(v);
}
for (const [name, value, scope] of DATA.floats) {
  const v = ensureVar(c, name, 'FLOAT'); v.setValueForMode(M, value); v.scopes = [scope]; codeSyntax(v);
}
const existing = await figma.getLocalTextStylesAsync();
const styleIds = [];
for (const st of DATA.styles) {
  const fontName = styleFor(familyName[st.family], st.weight);
  if (!fontName) { report.warnings.push(`font missing for ${st.name}`); continue; }
  await figma.loadFontAsync(fontName);
  let ts = existing.find((x) => x.name === st.name);
  if (!ts) { ts = figma.createTextStyle(); ts.name = st.name; report.created.push(ts.id); }
  ts.fontName = fontName;
  ts.letterSpacing = { unit: 'PIXELS', value: st.tracking };
  ts.textCase = st.upper ? 'UPPER' : 'ORIGINAL';
  ts.description = st.description;
  ts.setBoundVariable('fontSize', findVar('Typography', st.size));
  ts.setBoundVariable('lineHeight', findVar('Typography', st.line));
  styleIds.push(ts.id);
}
return { collection: c.id, textStyles: styleIds.length, styleIds, created: report.created.length, warnings: report.warnings };
"""

MOTION = r"""
// Motion: Standard and Reduced modes (reduced motion as a token mode, DC-L04-25). Easing is stored as a CSS
// cubic-bezier STRING; Figma's EASING type exists but its value shape was not verified (see figma-plan.md).
const c = ensureCollection('Motion', ['Standard', 'Reduced']);
const S = modeId(c, 'Standard'), R = modeId(c, 'Reduced');
const prim = (n) => findVar('Primitives', n);
const durType = prim(DATA.durations[0][1]).resolvedType;
for (const [name, target] of DATA.durations) {
  const v = ensureVar(c, name, durType); v.setValueForMode(S, alias(prim(target))); v.setValueForMode(R, alias(prim(target))); v.scopes = []; codeSyntax(v);
}
for (const [name, css, description] of DATA.easingRows) {
  const v = ensureVar(c, name, 'STRING'); v.setValueForMode(S, css); v.setValueForMode(R, css); v.scopes = []; v.description = description; codeSyntax(v);
}
for (const [name, dStd, dRed, eStd, eRed] of DATA.transitions) {
  const d = ensureVar(c, name + '/duration', durType);
  d.setValueForMode(S, alias(findVar('Motion', dStd))); d.setValueForMode(R, alias(findVar('Motion', dRed))); d.scopes = []; codeSyntax(d);
  const e = ensureVar(c, name + '/easing', 'STRING');
  e.setValueForMode(S, alias(findVar('Motion', eStd))); e.setValueForMode(R, alias(findVar('Motion', eRed))); e.scopes = []; codeSyntax(e);
}
return { collection: c.id, durationType: durType, variables: allVars.filter((v) => v.variableCollectionId === c.id).length, warnings: report.warnings };
"""

EFFECTS = r"""
// Effect styles whose shadow colors are bound to Color variables, so Light/Dark switches the shadow (DC-L04-12).
const existing = await figma.getLocalEffectStylesAsync();
const ids = [];
for (const st of DATA) {
  let es = existing.find((x) => x.name === st.name);
  if (!es) { es = figma.createEffectStyle(); es.name = st.name; report.created.push(es.id); }
  es.effects = st.layers.map((l) => figma.variables.setBoundVariableForEffect(
    { type: 'DROP_SHADOW', color: { r: 0, g: 0, b: 0, a: 0.1 }, offset: { x: l.x, y: l.y }, radius: l.blur, spread: l.spread,
      visible: true, blendMode: 'NORMAL', showShadowBehindNode: false }, 'color', findVar('Color', l.color)));
  es.description = st.description;
  ids.push(es.id);
}
return { effectStyles: ids, created: report.created.length };
"""

ICONS = r"""
// Icon components used by Button (instance swap needs a real component). Strokes bound to color/icon/default.
const page = figma.root.children.find((p) => p.name === 'Components');
if (!page) throw new Error('run 01-pages first');
await figma.setCurrentPageAsync(page);
const ICONS = {
  'icon/plus': '<svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 3.5v9M3.5 8h9" stroke="#000" stroke-width="1.5" stroke-linecap="round"/></svg>',
  'icon/spinner': '<svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 2.5a5.5 5.5 0 0 1 5.5 5.5" stroke="#000" stroke-width="2" stroke-linecap="round"/></svg>',
};
const iconColor = findVar('Color', 'color/icon/default');
const ids = {};
let x = 0;
for (const [name, svg] of Object.entries(ICONS)) {
  let comp = page.findOne((n) => n.type === 'COMPONENT' && n.name === name);
  if (!comp) {
    const node = figma.createNodeFromSvg(svg);
    comp = figma.createComponent(); comp.name = name; comp.resize(16, 16); comp.clipsContent = true;
    for (const child of [...node.children]) comp.appendChild(child);
    node.remove();
    comp.x = x; comp.y = -120; x += 40;
    report.created.push(comp.id);
  }
  comp.findAllWithCriteria({ types: ['VECTOR'] }).forEach((v) => {
    v.strokes = [figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: { r: 0, g: 0, b: 0 } }, 'color', iconColor)];
  });
  comp.description = name === 'icon/plus' ? 'Default leading icon for Button.' : 'Loading spinner for Button (replaces the icon).';
  ids[name] = comp.id;
}
return { icons: ids, created: report.created };
"""

BUTTON = r"""
// One component set per variant: Size (sm, md, lg) x State (6) = 18 variants, under Figma's 30-combination guidance.
// Properties: Label (text), Leading icon (boolean), Icon (instance swap). Every fill, stroke, size, padding, gap,
// radius and text style is bound to a variable or style (DC-L07-22, DC-L08-05, DC-L08-09).
const REBUILD = false; // set true to delete and rebuild this set
const page = figma.root.children.find((p) => p.name === 'Components');
if (!page) throw new Error('run 01-pages first');
await figma.setCurrentPageAsync(page);
const setName = `Button/${DATA.variant}`;
const old = page.findOne((n) => n.type === 'COMPONENT_SET' && n.name === setName);
if (old && !REBUILD) return { skipped: true, componentSetId: old.id, note: 'exists; set REBUILD = true to rebuild' };
if (old) old.remove();
const V = (col, name) => findVar(col, name);
const paint = (name) => figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: { r: 0, g: 0, b: 0 } }, 'color', V('Color', name));
const plus = page.findOne((n) => n.type === 'COMPONENT' && n.name === 'icon/plus');
const spin = page.findOne((n) => n.type === 'COMPONENT' && n.name === 'icon/spinner');
if (!plus || !spin) throw new Error('run 08-icons first');
const textStyle = (await figma.getLocalTextStylesAsync()).find((s) => s.name === 'text/label/lg');
const focusStyle = (await figma.getLocalEffectStylesAsync()).find((s) => s.name === 'focus/ring');
if (!textStyle || !focusStyle) throw new Error('run 05-typography and 07-effects first');
await figma.loadFontAsync(textStyle.fontName);
const SIZES = [['sm', 'space/inset/md', 16], ['md', 'space/inset/lg', 16], ['lg', 'space/inset/xl', 20]];
const STATES = ['Enabled', 'Hover', 'Focus-visible', 'Pressed', 'Disabled', 'Loading'];
const spec = DATA.spec;
const comps = [];
for (const [size, inset, iconPx] of SIZES) {
  for (const state of STATES) {
    const comp = figma.createComponent();
    comp.name = `Size=${size}, State=${state}`;
    comp.layoutMode = 'HORIZONTAL';
    comp.primaryAxisAlignItems = 'CENTER'; comp.counterAxisAlignItems = 'CENTER';
    comp.resize(120, 40);
    comp.primaryAxisSizingMode = 'AUTO'; comp.counterAxisSizingMode = 'FIXED';
    comp.setBoundVariable('height', V('Spacing', `size/control/${size}`));
    comp.setBoundVariable('paddingLeft', V('Spacing', inset)); comp.setBoundVariable('paddingRight', V('Spacing', inset));
    comp.paddingTop = 0; comp.paddingBottom = 0;
    comp.setBoundVariable('itemSpacing', V('Spacing', 'space/gap/sm'));
    for (const k of ['topLeftRadius', 'topRightRadius', 'bottomLeftRadius', 'bottomRightRadius']) comp.setBoundVariable(k, V('Radius', 'radius/control'));
    const disabled = state === 'Disabled';
    const fillName = disabled ? spec.disabledFill : ({ Hover: spec.hover, Pressed: spec.pressed }[state] || spec.rest);
    comp.fills = fillName ? [paint(fillName)] : [];
    const strokeName = spec.border ? (disabled ? 'color/border/subtle' : spec.border) : null;
    if (strokeName) { comp.strokes = [paint(strokeName)]; comp.strokeAlign = 'INSIDE'; comp.setBoundVariable('strokeWeight', V('Radius', 'border/width/default')); }
    if (state === 'Focus-visible') await comp.setEffectStyleIdAsync(focusStyle.id);
    const labelColor = disabled ? 'color/text/disabled' : spec.label;
    const icon = plus.createInstance(); icon.name = 'Leading icon'; icon.resize(iconPx, iconPx);
    const spinner = spin.createInstance(); spinner.name = 'Spinner'; spinner.resize(iconPx, iconPx);
    for (const inst of [icon, spinner]) inst.findAllWithCriteria({ types: ['VECTOR'] }).forEach((v) => { v.strokes = [paint(labelColor)]; });
    icon.visible = false; spinner.visible = state === 'Loading';
    const label = figma.createText();
    await label.setTextStyleIdAsync(textStyle.id);
    label.characters = DATA.label; label.name = 'Label';
    label.fills = [paint(labelColor)];
    comp.appendChild(icon); comp.appendChild(spinner); comp.appendChild(label);
    comps.push(comp);
  }
}
const set = figma.combineAsVariants(comps, page);
set.name = setName;
set.description = DATA.description;
// grid: columns = State, rows = Size
const colW = 180, rowH = 72, pad = 32;
set.children.forEach((child) => {
  const props = Object.fromEntries(child.name.split(', ').map((kv) => kv.split('=')));
  child.x = pad + STATES.indexOf(props.State) * colW;
  child.y = pad + SIZES.findIndex((s) => s[0] === props.Size) * rowH;
});
set.resizeWithoutConstraints(pad * 2 + STATES.length * colW - 40, pad * 2 + SIZES.length * rowH - 24);
set.x = 0; set.y = DATA.index * 320;
const labelKey = set.addComponentProperty('Label', 'TEXT', DATA.label);
const showKey = set.addComponentProperty('Leading icon', 'BOOLEAN', false);
const swapKey = set.addComponentProperty('Icon', 'INSTANCE_SWAP', plus.id);
for (const child of set.children) {
  const loading = child.name.endsWith('State=Loading');
  const lab = child.findOne((n) => n.type === 'TEXT' && n.name === 'Label');
  if (lab) lab.componentPropertyReferences = { characters: labelKey };
  const ic = child.findOne((n) => n.type === 'INSTANCE' && n.name === 'Leading icon');
  if (ic) ic.componentPropertyReferences = loading ? { mainComponent: swapKey } : { visible: showKey, mainComponent: swapKey };
}
return { componentSetId: set.id, variants: set.children.length, variantIds: set.children.map((c) => c.id) };
"""

VALIDATE = r"""
// Read-only check after all steps. Compare with the expected counts in figma-plan.md.
const cols = collections.map((c) => ({ name: c.name, modes: c.modes.map((m) => m.name), variables: allVars.filter((v) => v.variableCollectionId === c.id).length,
  unscopedSemantic: c.name === 'Primitives' ? 0 : allVars.filter((v) => v.variableCollectionId === c.id && v.scopes.includes('ALL_SCOPES')).length }));
const comp = figma.root.children.find((p) => p.name === 'Components');
if (comp) await figma.setCurrentPageAsync(comp);
const sets = comp ? comp.findAll((n) => n.type === 'COMPONENT_SET').map((s) => ({ name: s.name, variants: s.children.length,
  props: Object.keys(s.componentPropertyDefinitions) })) : [];
return { collections: cols, textStyles: (await figma.getLocalTextStylesAsync()).length, effectStyles: (await figma.getLocalEffectStylesAsync()).length, componentSets: sets };
"""


def main():
    files = {
        "00-inspect.js": script("00", "Inspect the file (read-only)", "Pages, collections, styles and the Inter / JetBrains Mono styles available.", None, INSPECT),
        "01-pages.js": script("01", "Pages", "Creates the five pages if missing.", None, PAGES),
        "02-primitives.js": script("02", "Primitives collection", "Color ramps, space, radius, border width and duration primitives.", primitives_data(), PRIMITIVES),
        "03-color.js": script("03", "Color collection (Light, Dark)", "Semantic color roles aliased to primitives.", color_data(), COLOR),
        "04-spacing-radius.js": script("04", "Spacing (Comfortable, Compact) and Radius collections", "Semantic spacing, sizes, radius, border and focus.", spacing_radius_data(), SPACING_RADIUS),
        "05-typography.js": script("05", "Typography collection and text styles", "Font variables and 15 text styles bound to them.", typography_data(), TYPOGRAPHY),
        "06-motion.js": script("06", "Motion collection (Standard, Reduced)", "Durations, easings and transitions.", motion_data(), MOTION),
        "07-effects.js": script("07", "Effect styles", "elevation/raised, elevation/overlay, focus/ring with variable-bound colors.", effects_data(), EFFECTS),
        "08-icons.js": script("08", "Icon components", "icon/plus and icon/spinner on the Components page.", None, ICONS),
    }
    for i, (variant, spec) in enumerate(BUTTON_VARIANTS.items()):
        data = {"variant": variant, "spec": spec, "label": BUTTON_LABELS[variant], "index": i,
                "description": f"Button, {variant.lower()} variant. Tokens: see design/atlas/03-button.html. One primary per view (DC-L08-05)."}
        files[f"{9 + i:02d}-button-{variant.lower()}.js"] = script(f"{9 + i:02d}", f"Button/{variant} component set", "18 variants, bound to variables and styles.", data, BUTTON)
    files["14-validate.js"] = script("14", "Validate (read-only)", "Counts collections, variables, styles and component sets.", None, VALIDATE)
    for name, body in files.items():
        with open(os.path.join(HERE, name), "w") as f:
            f.write(body)
        print(f"{name:28s} {len(body) / 1024:5.1f} KB")

    # Paper: tokens are CSS variables with no modes (S-L16-018), so the light values are the base set
    # and dark values get a "-dark" suffix. The atlas HTML uses literal values, so this list is for Paper's Theme tab.
    L, Dk = resolve("light"), resolve("dark")
    paper = []
    for p, t in L.items():
        r = t["resolved"]
        typ = t["$type"]
        css = "--" + p.replace(".", "-")
        if typ == "color" and p.startswith("color.") and p.count(".") >= 2 and not any(p.startswith(f"color.{h}.") for h in ("neutral", "accent", "success", "warning", "danger", "info")) and p not in ("color.white", "color.black"):
            for suffix, src in (("", L), ("-dark", Dk)):
                v = src[p]["resolved"]
                a = v.get("alpha", 1)
                value = v["hex"] if a == 1 else "rgba({},{},{},{})".format(*[int(v["hex"][i:i + 2], 16) for i in (1, 3, 5)], a)
                paper.append({"name": css + suffix, "type": "color", "value": value})
        elif typ == "dimension" and (p.startswith("space.inset") or p.startswith("space.gap") or p.startswith("space.layout")):
            paper.append({"name": css, "type": "spacing", "value": f"{r['value']:g}px"})
        elif typ == "dimension" and p.startswith("radius.") and not p.split(".")[1].isdigit():
            paper.append({"name": css, "type": "radius", "value": f"{r['value']:g}px"})
        elif typ == "dimension" and p.startswith("font.size."):
            paper.append({"name": css, "type": "font size", "value": f"{r['value']:g}px"})
        elif typ == "dimension" and p.startswith("font.lineHeight."):
            paper.append({"name": css, "type": "line height", "value": f"{r['value']:g}px"})
        elif typ == "fontWeight":
            paper.append({"name": css, "type": "font weight", "value": str(r)})
        elif typ == "fontFamily":
            paper.append({"name": css, "type": "font family", "value": r[0]})
    with open(os.path.join(HERE, "..", "atlas", "paper-tokens.json"), "w") as f:
        json.dump({"$description": "Paper create_tokens input (CSS variables; Paper has no modes, so dark values carry a -dark suffix). Generated by design/figma-scripts/build_scripts.py.",
                   "tokens": paper}, f, indent=0)
    print(f"paper-tokens.json: {len(paper)} tokens")


if __name__ == "__main__":
    main()
