#!/usr/bin/env python3
"""Build OpenDesigner's chunked knowledge from synthesis/ into the skill folders and data/.

Each skill must be self-contained (a claude.ai upload holds only the skill folder), so the
knowledge a skill needs is copied into its own references/ folder. data/ gets the same files
for consumers that are not skills (an MCP server, other tools).

    python3 tools/build_data.py            build everything
    python3 tools/build_data.py --check    exit 1 if any generated file is out of date

Inputs:  synthesis/questionnaire.json, levers.json, decision-graph.json, ontology.json,
         cards.json, glossary.json (when U1 has written it), research/L17 Part H (hook tables)
Outputs: skills/opendesigner/references/{stages/*.md, questions.json, levers.json, graph.json,
         ontology-slim.json, hooks.json, pacing.json, cards/*.json}; glossary.json in every skill
         skills/opendesigner-extract/references/reference-intake.json
         data/ (copy of the above), chatgpt-project/knowledge/ (at most 5 files)
Standard library only.
"""
import argparse, json, re, shutil, sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYN = ROOT / "synthesis"
SKILL = ROOT / "skills" / "opendesigner"
REF = SKILL / "references"
EXTRACT_REF = ROOT / "skills" / "opendesigner-extract" / "references"
DATA = ROOT / "data"
GPT = ROOT / "chatgpt-project" / "knowledge"
STAMP = "generated by tools/build_data.py from synthesis/; edit the source, not this file"

# Which visual template (skills/opendesigner/assets/templates/) previews each stage.
TEMPLATES = {
    "S03": "option-gallery.html", "S06": "option-gallery.html", "S07": "palette.html",
    "S08": "palette.html", "S09": "palette.html", "S10": "type-scale.html",
    "S11": "type-scale.html", "S12": "spacing-ruler.html", "S13": "spacing-ruler.html",
    "S14": "radius.html", "S15": "elevation.html", "S16": "motion.html",
    "S17": "component-sheet.html", "S20": "component-sheet.html",
    "S21": "component-sheet.html", "S22": "component-sheet.html", "S23": "component-sheet.html",
}


# Zoom levels replace the questionnaire's depth modes (BRIEF requirement 14, lane U2). Level 0 and 1 are
# hand-picked; the rest follow the questionnaire mode (Standard -> 2, Expert -> 3). [inferred; logged]
ZOOM_NAMES = {0: "sketch", 1: "broad", 2: "defined", 3: "detailed"}
ZOOM0 = ["Q-scope-01", "Q-aud-01", "Q-plat-01", "Q-brand-01", "Q-color-01", "Q-brand-03"]  # Q-brand-03 rides with Q-color-01
ZOOM1 = ["Q-dir-01", "Q-dir-02", "Q-color-02", "Q-type-01", "Q-shape-01", "Q-depth-01", "Q-motion-01", "Q-tool-01"]
# Areas a person can zoom into; section = the DESIGN.md heading the engine renders for it.
AREAS = [("overview", "The big picture", "Overview", ["S01", "S02", "S03", "S06"]),
         ("platforms", "Where it runs", "Platforms and Devices", ["S04"]),
         ("themes", "Light and dark", "Modes and Themes", ["S07"]),
         ("color", "Color", "Colors", ["S08", "S09"]),
         ("type", "Text", "Typography", ["S10", "S11"]),
         ("layout", "Spacing and layout", "Layout", ["S12", "S13"]),
         ("shape", "Corners", "Shapes", ["S14"]),
         ("depth", "Depth and shadows", "Elevation & Depth", ["S15"]),
         ("motion", "Motion and sound", "Motion", ["S16"]),
         ("imagery", "Icons and images", "Iconography and Imagery", ["S17", "S18"]),
         ("voice", "Words", "Content and Voice", ["S19"]),
         ("components", "Components", "Components", ["S20", "S21", "S22", "S23"]),
         ("delivery", "Files, tools and team", "For Agents", ["S05", "S24", "S25", "S26", "S27"])]
AREA_OF = {st: a[0] for a in AREAS for st in a[3]}
SECONDS = {"high": 60, "medium": 30, "low": 15}  # rough time per question by weight [inferred]


def zoom_of(x):
    if x["mode"] == "Any":
        return None
    if x["id"] in ZOOM0:
        return 0
    if x["id"] in ZOOM1:
        return 1
    return 2 if x["mode"] in ("Quick", "Standard") else 3


def load(name):
    return json.loads((SYN / name).read_text(encoding="utf-8"))


def slug(text):
    text = re.sub(r"\(.*?\)", "", text).lower()
    return re.sub(r"[^a-z0-9]+", "-", text).strip("-")[:40].rstrip("-")


def trim_sources(text):
    """Stage files keep Decision Card ids and drop raw source ids (the cards carry them), to stay short."""
    t = re.sub(r"S-L\d+-\d+", "", text or "")
    t = re.sub(r"\[\s*[,;\s]*\]", "", t)                      # brackets left empty
    t = re.sub(r"\[\s*[,;]\s*", "[", t)
    t = re.sub(r"\s*[,;]\s*(?=[,;\]])", "", t)
    t = re.sub(r"\[\s*(inferred)\s*\]", r"[\1]", t)
    return re.sub(r"  +", " ", t).replace(" .", ".").replace(" ,", ",").strip()


def val(v):
    return "|".join(map(str, v)) if isinstance(v, list) else str(v)


def dump(obj):
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":")) + "\n"


# ---------- graph ----------
def build_graph(q):
    g = load("decision-graph.json")
    kids = defaultdict(set)
    for e in g["edges"]:
        kids[e["source"]].add(e["target"])
    ov = load("graph-overrides.json")  # already merged by jev_nav.py graph; applied again idempotently
    for a in ov.get("add", []):
        kids[a[0]].add(a[1])
    for r in ov.get("remove", []):
        kids[r[0]].discard(r[1])

    def reach(n):
        seen, stack = set(), [n]
        while stack:
            for t in kids.get(stack.pop(), ()):
                if t not in seen:
                    seen.add(t); stack.append(t)
        seen.discard(n)
        return len(seen)

    asked_by = {}
    for x in q["questions"]:
        for c in x["decides"]:
            asked_by.setdefault(c, x["id"])
    nodes = {n["id"]: {"t": n["title"], "step": n["step"], "fan": len(kids.get(n["id"], ())),
                       "reach": reach(n["id"]), "q": asked_by.get(n["id"])} for n in g["nodes"]}
    top = sorted(nodes, key=lambda i: (-nodes[i]["fan"], -nodes[i]["reach"]))[:15]
    return {"_about": STAMP + ". nodes: t=title, fan=direct fan-out, reach=all downstream decisions, "
                      "q=question that decides it. edges: decision -> decisions it constrains.",
            "nodes": nodes, "edges": {k: sorted(v) for k, v in sorted(kids.items()) if v},
            "cycles": g.get("cycles", []), "top_fanout": top}


# ---------- questions ----------
def default_value(x):
    """The option value the prose default names, when it names exactly one (else None)."""
    d = (x["default"] or "").lower()
    hits = []
    for o in x["options"]:
        if isinstance(o["value"], list):
            continue
        v = str(o["value"]).lower()
        if re.match(r"^`?" + re.escape(v) + r"\b", d) or d.startswith(o["label"].lower()):
            hits.append(o["value"])
    return hits[0] if len(hits) == 1 else None


def build_questions(q):
    out = []
    for x in q["questions"]:
        out.append({"id": x["id"], "stage": x["stage"], "zoom": zoom_of(x), "area": AREA_OF.get(x["stage"]),
                    "mode": x["mode"], "kind": x["kind"],
                    "class": x["block_class"], "weight": x["time_weight"], "fan": x["fan_out"],
                    "ask": x["ask"], "options": [{"v": o["value"], "l": o["label"]} for o in x["options"]],
                    "default_value": default_value(x), "show_if": x["show_if"],
                    "decides": x["decides"], "changes": x["changes"], "template": TEMPLATES.get(x["stage"])})
    return {"_about": STAMP + ". Slim index of every question. default_value is set only when the prose "
                      "default names exactly one option; the prose default and everything else is in stages/*.md.",
            "zoom_levels": ZOOM_NAMES, "zoom0": ZOOM0, "zoom1": ZOOM1, "questions": out}


# ---------- stage files ----------
def stage_md(stage, qs, n_total, note="", detailed=False):
    tpl = TEMPLATES.get(stage["id"])
    counts = defaultdict(int)
    for x in qs:
        counts[zoom_of(x)] += 1
    zc = ", ".join(f"zoom {k} {ZOOM_NAMES[k]}: {counts[k]}" for k in sorted(k for k in counts if k is not None))
    lines = [f"# Stage {stage['n']:02d}: {stage['title']}" + (" (zoom 3, detailed)" if detailed else ""), "",
             f"<!-- {STAMP} -->", "",
             f"Area: `{AREA_OF.get(stage['id'], 'any')}` · {zc or 'open on every screen'} · visual: "
             + (f"`assets/templates/{tpl}`" if tpl else "text or the host question tool"), "",
             trim_sources(stage["screen"]) if not detailed else "Read the main stage file first; these questions refine it.", "",
             *([note, ""] if note else []),
             "Ask only the questions at or below the zoom level being worked, in this order, and only when *Show if* "
             "holds. Everything else keeps its default (`auto_default`). Explain a term the first time with "
             "`glossary.json`.", ""]
    for x in qs:
        z = zoom_of(x)
        dv = default_value(x)
        lines.append(f"## {x['id']} · {x['question']}")
        lines.append(f"Zoom {z if z is not None else 'any'}{' ' + ZOOM_NAMES[z] if z is not None else ''} · "
                     f"weight {x['time_weight']} · changes {x['fan_out']} decisions · class {x['block_class'] or '-'}"
                     + (f" · cards {', '.join(x['decides'])}" if x["decides"] else ""))
        if x["show_if"]:
            lines.append(f"- **Show if:** {x['show_if']}")
        lines.append(f"- **Ask:** \"{x['ask']}\"")
        lines.append(f"- **Why:** {trim_sources(x['why'])}")
        lines.append("- **Options:**")
        opts = sorted(x["options"], key=lambda o: 0 if dv is not None and o["value"] == dv else 1)
        for o in opts:
            eff = trim_sources(o.get("effect"))
            lines.append(f"  - `{val(o['value'])}` {trim_sources(o['label'])}" + (f": {eff}" if eff else ""))
        lines.append(f"- **Default:** {('`' + str(dv) + '`: ') if dv is not None else ''}{trim_sources(x['default'])} "
                     f"*Source:* {trim_sources(x['default_source']) or '[inferred]'}")
        lines.append(f"- **Show:** {x['preview']}")
        if x["use_avoid"]:
            lines.append(f"- **Use / avoid:** {trim_sources(x['use_avoid'])}")
        if x["hook"]:
            h = x["hook"]
            lines.append(f"- **Hook:** accepts {trim_sources(h.get('accepts')) or '-'}"
                         + (f" If no: {trim_sources(h['if_no'])}" if h.get("if_no") else ""))
        lines.append(f"- **Skip:** {x['skip']}")
        lines.append("")
    return "\n".join(lines)


# ---------- ontology ----------
def first_sentence(text, cap=160):
    s = re.split(r"(?<=[.!?])\s", (text or "").strip(), maxsplit=1)[0]
    return s if len(s) <= cap else s[:cap - 1].rstrip() + "…"


def build_ontology():
    o = load("ontology.json")
    nodes = [{"id": n["id"], "name": n["name"], "parent": n.get("parent"), "prov": n.get("provenance"),
              "cards": n.get("cards", []), "def": first_sentence(n.get("definition"))} for n in o["nodes"]]
    return {"_about": STAMP + ". prov = provenance class (generatable, extractable, designer-owned, "
                      "tool-assisted); full text in synthesis/ontology.json.",
            "version": o["version"], "layers": o["layers"], "nodes": nodes}


# ---------- hooks (L17 Part H) ----------
def parse_hook_tables():
    text = (ROOT / "research" / "L17-how-systems-get-made.md").read_text(encoding="utf-8")
    part = text.split("## Part H.", 1)[1].split("## Part I.", 1)[0]
    h2, h3 = part.split("### H3.", 1)
    hooks = []
    for row in re.findall(r"^\| \*\*(H-[a-z0-9]+)\*\*(.*)$", h2, re.M):
        cells = [c.strip() for c in row[1].split(" | ")]
        cells[-1] = cells[-1].rstrip("|").strip()
        first = cells[0]
        hooks.append({"id": row[0], "kind": "asset", "name": re.sub(r"\s*\(.*$", "", first).strip(),
                      "questions": sorted(set(re.findall(r"Q-[a-z]+-\d+", first))),
                      "ask": cells[1].strip('"'), "accepts": cells[2], "does": cells[3],
                      "if_no": cells[4], "checks": cells[5], "evidence": cells[6] if len(cells) > 6 else ""})
    for row in re.findall(r"^\| \*\*(H-[a-z0-9]+)\*\*(.*)$", h3, re.M):
        cells = [c.strip() for c in row[1].split(" | ")]
        cells[-1] = cells[-1].rstrip("|").strip()
        hooks.append({"id": row[0], "kind": "tool", "blocks": cells[0], "ask": cells[1].strip('"'),
                      "tools": cells[2], "caveat": cells[3], "checks": cells[4],
                      "evidence": cells[5] if len(cells) > 5 else ""})
    return hooks


# Hooks whose L17 row names no question id; mapped here by topic [inferred].
EXTRA_HOOK_Q = {"H-favicon": ["Q-brand-03"], "H-motif": ["Q-img-07", "Q-shape-05"],
                "H-haptic": ["Q-motion-09"], "H-brandbook": ["Q-ref-01"]}


def build_hooks(q):
    hooks = parse_hook_tables()
    for h in hooks:
        if h["kind"] == "asset" and not h["questions"]:
            h["questions"] = EXTRA_HOOK_Q.get(h["id"], [])
    by_q = {x["id"]: x for x in q["questions"]}
    for h in hooks:
        for qid in h.get("questions", []):
            if qid in by_q and by_q[qid]["hook"]:
                h.setdefault("questionnaire", {})[qid] = by_q[qid]["hook"]
    status = ["have", "commissioning", "tool", "open-library", "placeholder", "not-needed"]
    return {"_about": STAMP + " and research/L17 Part H. One asset or tool hook per row.",
            "checklist_question": "Q-brand-08", "statuses": status, "hooks": hooks}


# ---------- pacing ----------
def build_pacing(q, graph):
    qs = q["questions"]
    per_stage = defaultdict(lambda: {"quick": 0, "standard": 0, "expert": 0, "high": 0, "medium": 0, "low": 0})
    for x in qs:
        s = per_stage[x["stage"]]
        for m in x["modes"]:
            s[m] += 1
        s[x["time_weight"]] += 1
    deep_always = [x["id"] for x in qs if re.search(
        r"contrast|reduc\w* motion|accessib|target size", x["question"], re.I)]
    top = [{"card": c, "title": graph["nodes"][c]["t"], "fan": graph["nodes"][c]["fan"],
            "reach": graph["nodes"][c]["reach"], "q": graph["nodes"][c]["q"]} for c in graph["top_fanout"]]
    areas = []
    for aid, name, section, stages in AREAS:
        levels = {}
        for z in (0, 1, 2, 3):
            ids = [x["id"] for x in qs if x["stage"] in stages and zoom_of(x) == z]
            secs = sum(SECONDS[x["time_weight"]] for x in qs if x["id"] in ids)
            if ids:
                levels[str(z)] = {"questions": ids, "minutes": max(1, round(secs / 60))}
        areas.append({"id": aid, "name": name, "section": section, "stages": stages, "levels": levels})
    return {"_about": STAMP + ". Where the interview spends time (DC-L18-08, DC-L17-08). minutes are rough "
                      "estimates from the time weight (high 60 s, medium 30 s, low 15 s) [inferred].",
            "zoom_levels": ZOOM_NAMES, "zoom0": ZOOM0, "zoom1": ZOOM1, "areas": areas,
            "counts": q["meta"]["counts"],
            "time_weight_rule": q["meta"]["time_weight_rule"],
            "thresholds": {"fanout_deep": 5, "show_visual_if_reach_gt": 20, "inferred": True},
            "deep_always": deep_always, "top_decisions": top,
            "assumed_owner_inputs_below_zoom2": q["meta"]["quick_mode_assumed_owner_inputs"],
            "gates": q["interview_protocol"][11], "per_stage": dict(sorted(per_stage.items()))}


# ---------- cards ----------
def build_cards():
    by_lane = defaultdict(list)
    for c in load("cards.json"):
        d = re.sub(r"\s+", " ", c.get("default") or "").strip()
        by_lane[c["lane"]].append({"id": c["id"], "title": c["title"], "block": c["block path"],
                                   "default": d if len(d) <= 700 else d[:699] + "…",
                                   "src": f"{c['file']}:{c['line']}"})
    return by_lane


def build_intake():
    lv = load("levers.json")
    return {"_about": STAMP + " (levers.json: referenceIntake and dials). See synthesis/LEVERS.md section E.",
            "referenceIntake": lv["referenceIntake"],
            "dials": [{k: d[k] for k in ("id", "left", "right", "default", "definition", "drives") if k in d}
                      for d in lv["dials"]],
            "raw": [r["id"] for r in lv["raw"]]}


# ---------- glossary (written by lane U1; shipped only when it exists) ----------
def build_glossary():
    src = SYN / "glossary.json"
    if not src.exists():
        return None
    g = json.loads(src.read_text(encoding="utf-8"))
    terms = g.get("terms", g) if isinstance(g, dict) else g
    body = ",\n".join(json.dumps(t, ensure_ascii=False, separators=(",", ":")) for t in terms)
    return ('{"_about":"' + STAMP + '. One term per line: search for the term or an alias, read that line. '
            'Voices: plain first; designer and engineer on request.",\n"terms":[\n' + body + "\n]}\n")


# ---------- write ----------
def outputs():
    q = load("questionnaire.json")
    files = {}
    graph = build_graph(q)
    by_stage = defaultdict(list)
    for x in q["questions"]:
        by_stage[x["stage"]].append(x)
    for s in q["stages"]:
        order = {qid: i for i, qid in enumerate(s["questions"])}
        qs = sorted(by_stage[s["id"]], key=lambda x: order.get(x["id"], 999))
        base = f"stages/{s['n']:02d}-{slug(s['title'])}"
        main = [x for x in qs if zoom_of(x) != 3]
        detail = [x for x in qs if zoom_of(x) == 3]
        files[base + ".md"] = stage_md(s, main, len(q["questions"]),
                                       note=f"Zoom 3 (detailed) questions: `{base.split('/')[1]}.detailed.md`." if detail else "")
        if detail:
            files[base + ".detailed.md"] = stage_md(s, detail, len(q["questions"]), detailed=True)
    files["questions.json"] = dump(build_questions(q))
    files["levers.json"] = (SYN / "levers.json").read_text(encoding="utf-8")
    files["graph.json"] = dump(graph)
    files["ontology-slim.json"] = dump(build_ontology())
    files["hooks.json"] = dump(build_hooks(q))
    files["pacing.json"] = dump(build_pacing(q, graph))
    for lane, cards in sorted(build_cards().items()):
        files[f"cards/{lane}.json"] = dump({"_about": STAMP, "cards": cards})
    return files


def gpt_files(ref_files, glossary=None):
    """Up to 5 knowledge files for a ChatGPT Project (Free allows 5)."""
    def read(p):
        return p.read_text(encoding="utf-8") if p.exists() else ""
    skill = re.sub(r"^---.*?---\n", "", read(SKILL / "SKILL.md"), flags=re.S)
    parts = [skill] + [read(REF / n) for n in ("zoom.md", "rules.md", "improve.md", "guardrails.md", "hooks.md")]
    for n in ("DESIGN.md", "decisions.md", "RATIONALE.md", "AGENTS-snippet.md", "state.json"):
        body = read(SKILL / "assets" / "output" / n)
        if body:
            parts.append(f"## Output template: {n}\n\n```\n{body.strip()}\n```")
    stages = "\n\n".join(v for k, v in sorted(ref_files.items(), key=lambda kv: (kv[0].replace(".detailed", ""), ".detailed" in kv[0]))
                           if k.startswith("stages/"))
    lookup = {"graph": json.loads(ref_files["graph.json"]), "ontology": json.loads(ref_files["ontology-slim.json"]),
              "hooks": json.loads(ref_files["hooks.json"]), "pacing": json.loads(ref_files["pacing.json"]),
              "questions": json.loads(ref_files["questions.json"])}
    if glossary:
        lookup["glossary"] = json.loads(glossary)["terms"]
    out = {"01-protocol.md": "\n\n".join(p.strip() for p in parts if p.strip()) + "\n",
           "02-stages.md": stages, "03-levers.json": ref_files["levers.json"],
           "04-lookup.json": dump(lookup)}
    engine = SKILL / "scripts" / "engine.py"
    if engine.exists():
        out["05-engine.py"] = read(engine)
    return out


def targets():
    ref = outputs()
    t = {}
    for k, v in ref.items():
        t[REF / k] = v
        t[DATA / k] = v
    intake = dump(build_intake())
    t[EXTRACT_REF / "reference-intake.json"] = intake
    t[DATA / "reference-intake.json"] = intake
    glossary = build_glossary()
    if glossary:
        for skill in sorted((ROOT / "skills").iterdir()):
            if (skill / "SKILL.md").exists():
                t[skill / "references" / "glossary.json"] = glossary
        t[DATA / "glossary.json"] = glossary
    for k, v in gpt_files(ref, glossary).items():
        t[GPT / k] = v
    return t


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if generated files are stale")
    args = ap.parse_args()
    t = targets()
    stale = [p for p, v in t.items() if not p.exists() or p.read_text(encoding="utf-8") != v]
    managed = [REF / "stages", REF / "cards", DATA / "stages", DATA / "cards", GPT]
    extra = [f for d in managed if d.exists() for f in d.iterdir() if f.is_file() and f not in t]
    if args.check:
        for p in stale + extra:
            print("stale:", p.relative_to(ROOT))
        sys.exit(1 if stale or extra else 0)
    for f in extra:
        f.unlink()
    for p in stale:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(t[p], encoding="utf-8")
    big = sorted(((len(v.encode()), p) for p, v in t.items() if p.is_relative_to(REF)), reverse=True)[:3]
    print(f"{len(t)} files, {len(stale)} written, {len(extra)} removed. Largest in the skill: "
          + ", ".join(f"{p.relative_to(REF)} {n // 1024} KB" for n, p in big))


if __name__ == "__main__":
    main()
